### ISSUE TITLE
Closing announcement window

### ISSUE THREAD

**Issue by frgooall** [thoughtbot/paul_revere#31]
Is it possible to have a user close the announcement message?  I see using the #announcement id you can style the message, but would like to have the user be able to close it...There probably is a simple answer.

**Comment by mjankowski** [comment]
There should be a "hide" link included in the partial, which uses client-side JS to hide the message, and store that messages ID so that it doesn't show up anymore.

Are you not seeing the hide link, or is it not working like that?

**Comment by frgooall** [comment]
Hey! I don't see the hide link... Could there be conflict with front-end library... Using bootstrap.

---Sent from Boxer | http://getboxer.com

On July 29, 2015 at 10:29:22 AM EDT, Matt Jankowski <notifications@github.com> wrote:There should be a "hide" link included in the partial, which uses client-side JS to hide the message, and store that messages ID so that it doesn't show up anymore.  Are you not seeing the hide link, or is it not working like that?  —Reply to this email directly or view it on GitHub.

**Comment by mjankowski** [comment]
Can you either provide a sample app that reproduces the failure, or some code snippets from your app where it's failing?

**Comment by frgooall** [comment]
I will provide you access to the repo where Im having the issue...it call usfh foundation app.

**Comment by frgooall** [comment]
Did you have a chance to see what the issue with hide link? I gave you access to the repo? Let me know if there is something else you need!  Thanks for your help!

**Comment by mjankowski** [comment]
I don't think you gave me access.

**Comment by frgooall** [comment]
What is your github username?

-- 
Fritz Rodriguez Jr.
Founder/Lead Developer
Simply Brilliant Media, LLC
fritz@simplybrilliantmedia.com


On August 1, 2015 at 11:05:36 AM, Matt Jankowski (notifications@github.com) wrote:

I don't think you gave me access.

**Comment by frgooall** [comment]
here is the screenshot of the repo I gave you access to 

<img width="1076" alt="screen shot 2015-08-01 at 11 32 21 am" src="https://cloud.githubusercontent.com/assets/329702/9022382/232471c8-3841-11e5-9fc0-cb2a62066399.png">

**Comment by frgooall** [comment]
I created a simple rails app and the hide displays, when I include bootstrap 3.3 the link disappears.

**Comment by mjankowski** [comment]
Great, thanks for confirming that.
