### ISSUE TITLE
Rails 5 support?

### ISSUE THREAD

**Issue by qazbnm456** [thoughtbot/paul_revere#32]
Excuse me, will paul_revere support Rails5?

**Comment by mjankowski** [comment]
Yes it will.  We generally try to have support for new rails versions right before or right around the time the new rails version itself is released.

**Comment by sonalkr132** [comment]
Hey. Rails is in rc, any update on this?

**Comment by mjankowski** [comment]
I just pushed a `2.1.0.rc1` release which has relaxed version requirements and should work with the rails 5 release candidate - let me know if you have any issues.
