### ISSUE TITLE
Authors may not be empty Heroku bundler Issue 

### ISSUE THREAD

**Issue by choilive** [thoughtbot/paul_revere#34]
It seems heroku does not like how the authors are generated for the gemspec ref commit `757629e`.

Bundler complains that the gemspec is not valid
`remote: The gemspec at [...]/paul_revere.gemspec is not valid. The validation error was 'authors may not be empty'`

Using bundler-1.11.2 and Ruby 2.2.0, pulling from the prepare for 2.1.0.rc1 commit  ref `2d99c8e`

**Comment by mjankowski** [comment]
Resolved in 2.1.0
