### ISSUE TITLE
Is this gem not supported anymore?

### ISSUE THREAD

**Issue by marvindanig** [thoughtbot/paul_revere#35]
It'd be nice if it were, especially on rails 5. The build status is currently showing as failing.

**Comment by choilive** [comment]
It doesn't seem like it is. 

The mj-versions branch's builds are passing, which is 2 commits ahead of master. I use this gem in a Rails 5 app, and the only issue I had was dealing with the authors in the gemspec when deploying to Heroku.

**Comment by simi** [comment]
Hello @mjankowski. Sorry for directly linking you, but you're probably the author of latest rc release. Is it possible to release 2.1? Are there any problems I can help with blocking this release?

It will be really handy for rubygems.org Rails 5 upgrade linked above.

**Comment by mjankowski** [comment]
I can take a look at this and push out a rails 5+ compatible release.

**Comment by mjankowski** [comment]
Should be resolved in 2.1.0, sorry that took so long!

**Comment by simi** [comment]
@mjankowski thanks!
