### ISSUE TITLE
rails generate paul_revere:views not working

### ISSUE THREAD

**Issue by hunterxx222** [thoughtbot/paul_revere#36]
After installing paul_revere I run the code it shows: 

> Expected string default value for '--jbuilder'; got true (boolean)
Expected boolean default value for '--markerb'; got :erb (string)
Could not find generator 'paul_revere:views'. Maybe you meant 'paul_revere', 'devise:views' or 'kaminari:views'
Run `rails generate --help` for more options.

**Comment by mjankowski** [comment]
I can't reproduce this ... can you provide either a sample app or a Rails version where this happens if still an issue?
