### ISSUE TITLE
Namespace announcement model

### ISSUE THREAD

**Issue by chamnap** [thoughtbot/paul_revere#38]
I guess it would be better if the `announcement` model is being under a namespace. Otherwise, it would be conflicted the host app.

**Comment by colinross** [comment]
Chances are that if your host app has defined a model named `Announcement`, you aren't using this gem, you are likely doing a lot more.

#own2cents

**Comment by mjankowski** [comment]
I'm going to close this because I don't think we plan on making this change.

If someone else wants to, I think either direction of:

- Use an actual namespace for the model and table
- Make the model name configurable

...are worth exploring.
